- name: Install utilities for debian based os
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=1800
  with_items:
    - git
    - python-dev
    - python-setuptools
    - python-pip
    - libxslt1-dev
    - libz-dev
